---
- name: Deploy web server on a virtual machine
  hosts: webservers
  become: yes
  tasks:
    - name: Ensure the web server is installed
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure the web server is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy a simple index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head>
            <title>Welcome to Your Web Server!</title>
          </head>
          <body>
            <h1>Hello, world!</h1>
            <p>This is a simple web server setup using Ansible.</p>
          </body>
          </html>
