apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  containers:
  - name: secure-container
    image: nginx:latest
    securityContext:
      runAsUser: 1000          # Run as non-root user with UID 1000
      runAsGroup: 3000         # Run with GID 3000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL                  # Drop all Linux capabilities
      readOnlyRootFilesystem: true # Make root filesystem read-only
  securityContext:
    fsGroup: 2000              # Set filesystem group to 2000
